### ISSUE TITLE
Instructions for Maven Beginners

### ISSUE THREAD

**Issue by stratebi** [stratebi/STPivot4#2]
### Structure

In this repository is the source code of STPivot. It is divided in two modules stpivot4 and stthemes-master. 

The result of compiling this project is a pentaho plugin (in .zip, .tar.gz o .rar, as you prefer).

The stpivot4 module depends on stthemes-master, that means that you have to compile properly the last one, for being available for the main module, stpivot4. 

### Maven dependencies
We use maven for dependency management, so yo have to install maven in your system in order to execute the command line instructions for playing with the stpivot4 plugin, compile changes, install a dependency, etc.

The pom.xml files of each projects refers to the pentaho repository, that unfortunately is removing artifacts continuously and is changing too much lately, for this reason we try to keep update on those changes, but not always we achieve this, maybe some dependencies are referenced in our pom.xml files does not exists en pentaho repository, in that case you need to update what has changed in pentaho repo and made the changes to the affected pom.xml files. All this until there is an stable repository, 

### Compile and Install
Once you have maven installed go to the stthemes-master directory and execute the following commands:

mvn compile
mvn install

Then, do the same in the stpivot4 directory 

### Usage
This steps generate the artifact needed by the plugin, and the plugin in a compressed file. If every has worked fine the plugin is in:

${home}/.m2/repository/com/stratebi/stpivot4/stpivot4-pentaho/1.0-SNAPSHOT/stpivot4-pentaho-1.0-SNAPSHOT-plugin.zip

The next step: decompress this file in: pentaho-solutions/system/

Restart pentaho and in the "Home" page, click "Create New" -> "STPivot4"

**Comment by DSantonastaso** [comment]
Thanks works fine :)

**Comment by guidorival** [comment]
Did not work for me running version 5.4. It ask for some dependencies. Any suggestions? 

This is the error (copied textually) :

 Failed to execute goal on project stpivot4-analytics: Could not resolve dependencies for project com.stratebi.stpivot4:stpivot4-analytics:war:1.0-SNAPSHOT: The following artifacts could not be resolved: pentaho:pentaho-platform-core:jar:5.4.0.1-130, pentaho:pentaho-platform-api:jar:5.4.0.1-130: Could not find artifact pentaho:pentaho-platform-core:jar:5.4.0.1-130 in prime-repo (http://repository.primefaces.org) -> [Help 1]

Any help would be much appreciated!

**Comment by aahahocevar** [comment]
Hi all.

I got this error on pentaho 6.1 after decompress the file and restart it:
`
2017-01-27 00:02:41,155 ERROR [org.pentaho.platform.web.servlet.PluginDispatchServlet] Could not load servlet 'stpivot4/faces'
java.lang.IllegalStateException: No Factories configured for this Application. This happens if the faces-initialization does not work at all - make sure that you properly include all configuration settings necessary for a basic faces application and that all the necessary libs are included. Also check the logging output of your web application and your container for any exceptions!
If you did that and find nothing, the mistake might be due to the fact that you use some special web-containers which do not support registering context-listeners via TLD files and a context listener is not setup in your web.xml.
A typical config looks like this;
<listener>
  <listener-class>org.apache.myfaces.webapp.StartupServletContextListener</listener-class>
</listener>
`

Any idea?
Thanks in advance

**Comment by joseraulperezrodriguez** [comment]
@aahahocevar , it seems ware, maybe an error on your environment, this works fine for me.

If you want to use it, ask for a compiled version @stratebi.

**Comment by deibidcode** [comment]
Hello,
It doesn't compile. It can't resolve a dependency to the library stpivot4-theme.jar. I search in the repository and it seems like doesn´t exist.
¿Where can I get this jar?

**Comment by stratebi** [comment]
@deibidcode we have fixed the dependencies of this repository, please, try again and see this works now.
